// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimedata.proto

package com.grpc.proto.smartproto;

public interface AirQualitySummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.AirQualitySummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>float pm25Value = 2;</code>
   */
  float getPm25Value();

  /**
   * <code>float pm10Value = 3;</code>
   */
  float getPm10Value();

  /**
   * <code>float ozoneValue = 4;</code>
   */
  float getOzoneValue();

  /**
   * <code>float airQualityIndex = 5;</code>
   */
  float getAirQualityIndex();
}
