// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public final class HistoryDataProtoImpl {
  private HistoryDataProtoImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_HistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_HistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_PMHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_PMHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_PMHistoryEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_PMHistoryEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_OzoneHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_OzoneHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_OzoneHistoryEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_OzoneHistoryEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_SummaryHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_SummaryHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_SummaryHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_SummaryHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_AirQualitySummaryHistory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_AirQualitySummaryHistory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_LocationHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_LocationHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_LocationHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_LocationHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_AirQualityByLocationHistory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_AirQualityByLocationHistory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rhistory.proto\022\nsmartproto\":\n\016HistoryRe" +
      "quest\022\014\n\004city\030\001 \001(\t\022\014\n\004area\030\002 \001(\t\022\014\n\004day" +
      "s\030\003 \001(\005\"@\n\021PMHistoryResponse\022+\n\007entries\030" +
      "\001 \003(\0132\032.smartproto.PMHistoryEntry\"2\n\016PMH" +
      "istoryEntry\022\021\n\ttimestamp\030\001 \001(\003\022\r\n\005value\030" +
      "\002 \001(\002\"F\n\024OzoneHistoryResponse\022.\n\007entries" +
      "\030\001 \003(\0132\035.smartproto.OzoneHistoryEntry\"5\n" +
      "\021OzoneHistoryEntry\022\021\n\ttimestamp\030\001 \001(\003\022\r\n" +
      "\005value\030\002 \001(\002\"3\n\025SummaryHistoryRequest\022\014\n" +
      "\004city\030\001 \001(\t\022\014\n\004days\030\002 \001(\005\"O\n\026SummaryHist" +
      "oryResponse\0225\n\007summary\030\001 \003(\0132$.smartprot" +
      "o.AirQualitySummaryHistory\"\277\001\n\030AirQualit" +
      "ySummaryHistory\022\014\n\004area\030\001 \001(\t\022/\n\013pm25His" +
      "tory\030\002 \003(\0132\032.smartproto.PMHistoryEntry\022/" +
      "\n\013pm10History\030\003 \003(\0132\032.smartproto.PMHisto" +
      "ryEntry\0223\n\014ozoneHistory\030\004 \003(\0132\035.smartpro" +
      "to.OzoneHistoryEntry\"K\n\026LocationHistoryR" +
      "equest\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlongitude\030\002 " +
      "\001(\002\022\014\n\004days\030\003 \001(\005\"Z\n\027LocationHistoryResp" +
      "onse\022?\n\016airQualityList\030\001 \003(\0132\'.smartprot" +
      "o.AirQualityByLocationHistory\"\302\001\n\033AirQua" +
      "lityByLocationHistory\022\014\n\004area\030\001 \001(\t\022/\n\013p" +
      "m25History\030\002 \003(\0132\032.smartproto.PMHistoryE" +
      "ntry\022/\n\013pm10History\030\003 \003(\0132\032.smartproto.P" +
      "MHistoryEntry\0223\n\014ozoneHistory\030\004 \003(\0132\035.sm" +
      "artproto.OzoneHistoryEntry2\340\003\n\030AirQualit" +
      "yHistoryService\022M\n\016GetPM25History\022\032.smar" +
      "tproto.HistoryRequest\032\035.smartproto.PMHis" +
      "toryResponse\"\000\022M\n\016GetPM10History\022\032.smart" +
      "proto.HistoryRequest\032\035.smartproto.PMHist" +
      "oryResponse\"\000\022Q\n\017GetOzoneHistory\022\032.smart" +
      "proto.HistoryRequest\032 .smartproto.OzoneH" +
      "istoryResponse\"\000\022f\n\033GetAirQualitySummary" +
      "History\022!.smartproto.SummaryHistoryReque" +
      "st\032\".smartproto.SummaryHistoryResponse\"\000" +
      "\022k\n\036GetAirQualityByLocationHistory\022\".sma" +
      "rtproto.LocationHistoryRequest\032#.smartpr" +
      "oto.LocationHistoryResponse\"\000B3\n\031com.grp" +
      "c.proto.smartprotoB\024HistoryDataProtoImpl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartproto_HistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartproto_HistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_HistoryRequest_descriptor,
        new java.lang.String[] { "City", "Area", "Days", });
    internal_static_smartproto_PMHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartproto_PMHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_PMHistoryResponse_descriptor,
        new java.lang.String[] { "Entries", });
    internal_static_smartproto_PMHistoryEntry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartproto_PMHistoryEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_PMHistoryEntry_descriptor,
        new java.lang.String[] { "Timestamp", "Value", });
    internal_static_smartproto_OzoneHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartproto_OzoneHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_OzoneHistoryResponse_descriptor,
        new java.lang.String[] { "Entries", });
    internal_static_smartproto_OzoneHistoryEntry_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smartproto_OzoneHistoryEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_OzoneHistoryEntry_descriptor,
        new java.lang.String[] { "Timestamp", "Value", });
    internal_static_smartproto_SummaryHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_smartproto_SummaryHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_SummaryHistoryRequest_descriptor,
        new java.lang.String[] { "City", "Days", });
    internal_static_smartproto_SummaryHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_smartproto_SummaryHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_SummaryHistoryResponse_descriptor,
        new java.lang.String[] { "Summary", });
    internal_static_smartproto_AirQualitySummaryHistory_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_smartproto_AirQualitySummaryHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_AirQualitySummaryHistory_descriptor,
        new java.lang.String[] { "Area", "Pm25History", "Pm10History", "OzoneHistory", });
    internal_static_smartproto_LocationHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_smartproto_LocationHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_LocationHistoryRequest_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Days", });
    internal_static_smartproto_LocationHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_smartproto_LocationHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_LocationHistoryResponse_descriptor,
        new java.lang.String[] { "AirQualityList", });
    internal_static_smartproto_AirQualityByLocationHistory_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_smartproto_AirQualityByLocationHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_AirQualityByLocationHistory_descriptor,
        new java.lang.String[] { "Area", "Pm25History", "Pm10History", "OzoneHistory", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
