// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allerts.proto

package com.grpc.proto.smartproto;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float latitude = 1;</code>
   */
  float getLatitude();

  /**
   * <code>float longitude = 2;</code>
   */
  float getLongitude();
}
