// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimedata.proto

package com.grpc.proto.smartproto;

public interface LocationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.LocationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float latitude = 1;</code>
   */
  float getLatitude();

  /**
   * <code>float longitude = 2;</code>
   */
  float getLongitude();
}
