// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public interface LocationHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.LocationHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float latitude = 1;</code>
   */
  float getLatitude();

  /**
   * <code>float longitude = 2;</code>
   */
  float getLongitude();

  /**
   * <pre>
   * Number of days to retrieve historical data for
   * </pre>
   *
   * <code>int32 days = 3;</code>
   */
  int getDays();
}
