// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public interface OzoneHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.OzoneHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .smartproto.OzoneHistoryEntry entries = 1;</code>
   */
  java.util.List<com.grpc.proto.smartproto.OzoneHistoryEntry> 
      getEntriesList();
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry entries = 1;</code>
   */
  com.grpc.proto.smartproto.OzoneHistoryEntry getEntries(int index);
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry entries = 1;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry entries = 1;</code>
   */
  com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder getEntriesOrBuilder(
      int index);
}
