// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimedata.proto

package com.grpc.proto.smartproto;

public interface PMRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.PMRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string area = 2;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 2;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();
}
