// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public interface SummaryHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.SummaryHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   * Number of days to retrieve historical data for
   * </pre>
   *
   * <code>int32 days = 2;</code>
   */
  int getDays();
}
