// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public interface SummaryHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.SummaryHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  java.util.List<com.grpc.proto.smartproto.AirQualitySummaryHistory> 
      getSummaryList();
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  com.grpc.proto.smartproto.AirQualitySummaryHistory getSummary(int index);
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  int getSummaryCount();
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder> 
      getSummaryOrBuilderList();
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder getSummaryOrBuilder(
      int index);
}
