// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

/**
 * Protobuf type {@code smartproto.SummaryHistoryResponse}
 */
public  final class SummaryHistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartproto.SummaryHistoryResponse)
    SummaryHistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SummaryHistoryResponse.newBuilder() to construct.
  private SummaryHistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SummaryHistoryResponse() {
    summary_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SummaryHistoryResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              summary_ = new java.util.ArrayList<com.grpc.proto.smartproto.AirQualitySummaryHistory>();
              mutable_bitField0_ |= 0x00000001;
            }
            summary_.add(
                input.readMessage(com.grpc.proto.smartproto.AirQualitySummaryHistory.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        summary_ = java.util.Collections.unmodifiableList(summary_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_SummaryHistoryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_SummaryHistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.proto.smartproto.SummaryHistoryResponse.class, com.grpc.proto.smartproto.SummaryHistoryResponse.Builder.class);
  }

  public static final int SUMMARY_FIELD_NUMBER = 1;
  private java.util.List<com.grpc.proto.smartproto.AirQualitySummaryHistory> summary_;
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  public java.util.List<com.grpc.proto.smartproto.AirQualitySummaryHistory> getSummaryList() {
    return summary_;
  }
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  public java.util.List<? extends com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder> 
      getSummaryOrBuilderList() {
    return summary_;
  }
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  public int getSummaryCount() {
    return summary_.size();
  }
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  public com.grpc.proto.smartproto.AirQualitySummaryHistory getSummary(int index) {
    return summary_.get(index);
  }
  /**
   * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
   */
  public com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder getSummaryOrBuilder(
      int index) {
    return summary_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < summary_.size(); i++) {
      output.writeMessage(1, summary_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < summary_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, summary_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.proto.smartproto.SummaryHistoryResponse)) {
      return super.equals(obj);
    }
    com.grpc.proto.smartproto.SummaryHistoryResponse other = (com.grpc.proto.smartproto.SummaryHistoryResponse) obj;

    boolean result = true;
    result = result && getSummaryList()
        .equals(other.getSummaryList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSummaryCount() > 0) {
      hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getSummaryList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.SummaryHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.proto.smartproto.SummaryHistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartproto.SummaryHistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartproto.SummaryHistoryResponse)
      com.grpc.proto.smartproto.SummaryHistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_SummaryHistoryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_SummaryHistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.proto.smartproto.SummaryHistoryResponse.class, com.grpc.proto.smartproto.SummaryHistoryResponse.Builder.class);
    }

    // Construct using com.grpc.proto.smartproto.SummaryHistoryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSummaryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (summaryBuilder_ == null) {
        summary_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        summaryBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_SummaryHistoryResponse_descriptor;
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.SummaryHistoryResponse getDefaultInstanceForType() {
      return com.grpc.proto.smartproto.SummaryHistoryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.SummaryHistoryResponse build() {
      com.grpc.proto.smartproto.SummaryHistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.SummaryHistoryResponse buildPartial() {
      com.grpc.proto.smartproto.SummaryHistoryResponse result = new com.grpc.proto.smartproto.SummaryHistoryResponse(this);
      int from_bitField0_ = bitField0_;
      if (summaryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          summary_ = java.util.Collections.unmodifiableList(summary_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.summary_ = summary_;
      } else {
        result.summary_ = summaryBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.proto.smartproto.SummaryHistoryResponse) {
        return mergeFrom((com.grpc.proto.smartproto.SummaryHistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.proto.smartproto.SummaryHistoryResponse other) {
      if (other == com.grpc.proto.smartproto.SummaryHistoryResponse.getDefaultInstance()) return this;
      if (summaryBuilder_ == null) {
        if (!other.summary_.isEmpty()) {
          if (summary_.isEmpty()) {
            summary_ = other.summary_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSummaryIsMutable();
            summary_.addAll(other.summary_);
          }
          onChanged();
        }
      } else {
        if (!other.summary_.isEmpty()) {
          if (summaryBuilder_.isEmpty()) {
            summaryBuilder_.dispose();
            summaryBuilder_ = null;
            summary_ = other.summary_;
            bitField0_ = (bitField0_ & ~0x00000001);
            summaryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSummaryFieldBuilder() : null;
          } else {
            summaryBuilder_.addAllMessages(other.summary_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.proto.smartproto.SummaryHistoryResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.proto.smartproto.SummaryHistoryResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.grpc.proto.smartproto.AirQualitySummaryHistory> summary_ =
      java.util.Collections.emptyList();
    private void ensureSummaryIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        summary_ = new java.util.ArrayList<com.grpc.proto.smartproto.AirQualitySummaryHistory>(summary_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.AirQualitySummaryHistory, com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder, com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder> summaryBuilder_;

    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.AirQualitySummaryHistory> getSummaryList() {
      if (summaryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(summary_);
      } else {
        return summaryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public int getSummaryCount() {
      if (summaryBuilder_ == null) {
        return summary_.size();
      } else {
        return summaryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualitySummaryHistory getSummary(int index) {
      if (summaryBuilder_ == null) {
        return summary_.get(index);
      } else {
        return summaryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder setSummary(
        int index, com.grpc.proto.smartproto.AirQualitySummaryHistory value) {
      if (summaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummaryIsMutable();
        summary_.set(index, value);
        onChanged();
      } else {
        summaryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder setSummary(
        int index, com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder builderForValue) {
      if (summaryBuilder_ == null) {
        ensureSummaryIsMutable();
        summary_.set(index, builderForValue.build());
        onChanged();
      } else {
        summaryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder addSummary(com.grpc.proto.smartproto.AirQualitySummaryHistory value) {
      if (summaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummaryIsMutable();
        summary_.add(value);
        onChanged();
      } else {
        summaryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder addSummary(
        int index, com.grpc.proto.smartproto.AirQualitySummaryHistory value) {
      if (summaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummaryIsMutable();
        summary_.add(index, value);
        onChanged();
      } else {
        summaryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder addSummary(
        com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder builderForValue) {
      if (summaryBuilder_ == null) {
        ensureSummaryIsMutable();
        summary_.add(builderForValue.build());
        onChanged();
      } else {
        summaryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder addSummary(
        int index, com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder builderForValue) {
      if (summaryBuilder_ == null) {
        ensureSummaryIsMutable();
        summary_.add(index, builderForValue.build());
        onChanged();
      } else {
        summaryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder addAllSummary(
        java.lang.Iterable<? extends com.grpc.proto.smartproto.AirQualitySummaryHistory> values) {
      if (summaryBuilder_ == null) {
        ensureSummaryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, summary_);
        onChanged();
      } else {
        summaryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder clearSummary() {
      if (summaryBuilder_ == null) {
        summary_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        summaryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public Builder removeSummary(int index) {
      if (summaryBuilder_ == null) {
        ensureSummaryIsMutable();
        summary_.remove(index);
        onChanged();
      } else {
        summaryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder getSummaryBuilder(
        int index) {
      return getSummaryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder getSummaryOrBuilder(
        int index) {
      if (summaryBuilder_ == null) {
        return summary_.get(index);  } else {
        return summaryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public java.util.List<? extends com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder> 
         getSummaryOrBuilderList() {
      if (summaryBuilder_ != null) {
        return summaryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(summary_);
      }
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder addSummaryBuilder() {
      return getSummaryFieldBuilder().addBuilder(
          com.grpc.proto.smartproto.AirQualitySummaryHistory.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder addSummaryBuilder(
        int index) {
      return getSummaryFieldBuilder().addBuilder(
          index, com.grpc.proto.smartproto.AirQualitySummaryHistory.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.AirQualitySummaryHistory summary = 1;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder> 
         getSummaryBuilderList() {
      return getSummaryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.AirQualitySummaryHistory, com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder, com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder> 
        getSummaryFieldBuilder() {
      if (summaryBuilder_ == null) {
        summaryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.proto.smartproto.AirQualitySummaryHistory, com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder, com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder>(
                summary_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        summary_ = null;
      }
      return summaryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartproto.SummaryHistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:smartproto.SummaryHistoryResponse)
  private static final com.grpc.proto.smartproto.SummaryHistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.proto.smartproto.SummaryHistoryResponse();
  }

  public static com.grpc.proto.smartproto.SummaryHistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SummaryHistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<SummaryHistoryResponse>() {
    @java.lang.Override
    public SummaryHistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SummaryHistoryResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SummaryHistoryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SummaryHistoryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.proto.smartproto.SummaryHistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

