// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimedata.proto

package com.grpc.proto.smartproto;

/**
 * Protobuf type {@code smartproto.AirQualityByLocation}
 */
public  final class AirQualityByLocation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartproto.AirQualityByLocation)
    AirQualityByLocationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AirQualityByLocation.newBuilder() to construct.
  private AirQualityByLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AirQualityByLocation() {
    area_ = "";
    pm25Value_ = 0F;
    pm10Value_ = 0F;
    ozoneValue_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AirQualityByLocation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            area_ = s;
            break;
          }
          case 21: {

            pm25Value_ = input.readFloat();
            break;
          }
          case 29: {

            pm10Value_ = input.readFloat();
            break;
          }
          case 37: {

            ozoneValue_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_AirQualityByLocation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_AirQualityByLocation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.proto.smartproto.AirQualityByLocation.class, com.grpc.proto.smartproto.AirQualityByLocation.Builder.class);
  }

  public static final int AREA_FIELD_NUMBER = 1;
  private volatile java.lang.Object area_;
  /**
   * <code>string area = 1;</code>
   */
  public java.lang.String getArea() {
    java.lang.Object ref = area_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      area_ = s;
      return s;
    }
  }
  /**
   * <code>string area = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAreaBytes() {
    java.lang.Object ref = area_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      area_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PM25VALUE_FIELD_NUMBER = 2;
  private float pm25Value_;
  /**
   * <code>float pm25Value = 2;</code>
   */
  public float getPm25Value() {
    return pm25Value_;
  }

  public static final int PM10VALUE_FIELD_NUMBER = 3;
  private float pm10Value_;
  /**
   * <code>float pm10Value = 3;</code>
   */
  public float getPm10Value() {
    return pm10Value_;
  }

  public static final int OZONEVALUE_FIELD_NUMBER = 4;
  private float ozoneValue_;
  /**
   * <code>float ozoneValue = 4;</code>
   */
  public float getOzoneValue() {
    return ozoneValue_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAreaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, area_);
    }
    if (pm25Value_ != 0F) {
      output.writeFloat(2, pm25Value_);
    }
    if (pm10Value_ != 0F) {
      output.writeFloat(3, pm10Value_);
    }
    if (ozoneValue_ != 0F) {
      output.writeFloat(4, ozoneValue_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAreaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, area_);
    }
    if (pm25Value_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, pm25Value_);
    }
    if (pm10Value_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, pm10Value_);
    }
    if (ozoneValue_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, ozoneValue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.proto.smartproto.AirQualityByLocation)) {
      return super.equals(obj);
    }
    com.grpc.proto.smartproto.AirQualityByLocation other = (com.grpc.proto.smartproto.AirQualityByLocation) obj;

    boolean result = true;
    result = result && getArea()
        .equals(other.getArea());
    result = result && (
        java.lang.Float.floatToIntBits(getPm25Value())
        == java.lang.Float.floatToIntBits(
            other.getPm25Value()));
    result = result && (
        java.lang.Float.floatToIntBits(getPm10Value())
        == java.lang.Float.floatToIntBits(
            other.getPm10Value()));
    result = result && (
        java.lang.Float.floatToIntBits(getOzoneValue())
        == java.lang.Float.floatToIntBits(
            other.getOzoneValue()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AREA_FIELD_NUMBER;
    hash = (53 * hash) + getArea().hashCode();
    hash = (37 * hash) + PM25VALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPm25Value());
    hash = (37 * hash) + PM10VALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPm10Value());
    hash = (37 * hash) + OZONEVALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getOzoneValue());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.AirQualityByLocation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.proto.smartproto.AirQualityByLocation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartproto.AirQualityByLocation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartproto.AirQualityByLocation)
      com.grpc.proto.smartproto.AirQualityByLocationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_AirQualityByLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_AirQualityByLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.proto.smartproto.AirQualityByLocation.class, com.grpc.proto.smartproto.AirQualityByLocation.Builder.class);
    }

    // Construct using com.grpc.proto.smartproto.AirQualityByLocation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      area_ = "";

      pm25Value_ = 0F;

      pm10Value_ = 0F;

      ozoneValue_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_AirQualityByLocation_descriptor;
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.AirQualityByLocation getDefaultInstanceForType() {
      return com.grpc.proto.smartproto.AirQualityByLocation.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.AirQualityByLocation build() {
      com.grpc.proto.smartproto.AirQualityByLocation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.AirQualityByLocation buildPartial() {
      com.grpc.proto.smartproto.AirQualityByLocation result = new com.grpc.proto.smartproto.AirQualityByLocation(this);
      result.area_ = area_;
      result.pm25Value_ = pm25Value_;
      result.pm10Value_ = pm10Value_;
      result.ozoneValue_ = ozoneValue_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.proto.smartproto.AirQualityByLocation) {
        return mergeFrom((com.grpc.proto.smartproto.AirQualityByLocation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.proto.smartproto.AirQualityByLocation other) {
      if (other == com.grpc.proto.smartproto.AirQualityByLocation.getDefaultInstance()) return this;
      if (!other.getArea().isEmpty()) {
        area_ = other.area_;
        onChanged();
      }
      if (other.getPm25Value() != 0F) {
        setPm25Value(other.getPm25Value());
      }
      if (other.getPm10Value() != 0F) {
        setPm10Value(other.getPm10Value());
      }
      if (other.getOzoneValue() != 0F) {
        setOzoneValue(other.getOzoneValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.proto.smartproto.AirQualityByLocation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.proto.smartproto.AirQualityByLocation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object area_ = "";
    /**
     * <code>string area = 1;</code>
     */
    public java.lang.String getArea() {
      java.lang.Object ref = area_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        area_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string area = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAreaBytes() {
      java.lang.Object ref = area_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        area_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string area = 1;</code>
     */
    public Builder setArea(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      area_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string area = 1;</code>
     */
    public Builder clearArea() {
      
      area_ = getDefaultInstance().getArea();
      onChanged();
      return this;
    }
    /**
     * <code>string area = 1;</code>
     */
    public Builder setAreaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      area_ = value;
      onChanged();
      return this;
    }

    private float pm25Value_ ;
    /**
     * <code>float pm25Value = 2;</code>
     */
    public float getPm25Value() {
      return pm25Value_;
    }
    /**
     * <code>float pm25Value = 2;</code>
     */
    public Builder setPm25Value(float value) {
      
      pm25Value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float pm25Value = 2;</code>
     */
    public Builder clearPm25Value() {
      
      pm25Value_ = 0F;
      onChanged();
      return this;
    }

    private float pm10Value_ ;
    /**
     * <code>float pm10Value = 3;</code>
     */
    public float getPm10Value() {
      return pm10Value_;
    }
    /**
     * <code>float pm10Value = 3;</code>
     */
    public Builder setPm10Value(float value) {
      
      pm10Value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float pm10Value = 3;</code>
     */
    public Builder clearPm10Value() {
      
      pm10Value_ = 0F;
      onChanged();
      return this;
    }

    private float ozoneValue_ ;
    /**
     * <code>float ozoneValue = 4;</code>
     */
    public float getOzoneValue() {
      return ozoneValue_;
    }
    /**
     * <code>float ozoneValue = 4;</code>
     */
    public Builder setOzoneValue(float value) {
      
      ozoneValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float ozoneValue = 4;</code>
     */
    public Builder clearOzoneValue() {
      
      ozoneValue_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartproto.AirQualityByLocation)
  }

  // @@protoc_insertion_point(class_scope:smartproto.AirQualityByLocation)
  private static final com.grpc.proto.smartproto.AirQualityByLocation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.proto.smartproto.AirQualityByLocation();
  }

  public static com.grpc.proto.smartproto.AirQualityByLocation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AirQualityByLocation>
      PARSER = new com.google.protobuf.AbstractParser<AirQualityByLocation>() {
    @java.lang.Override
    public AirQualityByLocation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AirQualityByLocation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AirQualityByLocation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AirQualityByLocation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.proto.smartproto.AirQualityByLocation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

