// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

/**
 * Protobuf type {@code smartproto.AirQualitySummaryHistory}
 */
public  final class AirQualitySummaryHistory extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartproto.AirQualitySummaryHistory)
    AirQualitySummaryHistoryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AirQualitySummaryHistory.newBuilder() to construct.
  private AirQualitySummaryHistory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AirQualitySummaryHistory() {
    area_ = "";
    pm25History_ = java.util.Collections.emptyList();
    pm10History_ = java.util.Collections.emptyList();
    ozoneHistory_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AirQualitySummaryHistory(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            area_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              pm25History_ = new java.util.ArrayList<com.grpc.proto.smartproto.PMHistoryEntry>();
              mutable_bitField0_ |= 0x00000002;
            }
            pm25History_.add(
                input.readMessage(com.grpc.proto.smartproto.PMHistoryEntry.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              pm10History_ = new java.util.ArrayList<com.grpc.proto.smartproto.PMHistoryEntry>();
              mutable_bitField0_ |= 0x00000004;
            }
            pm10History_.add(
                input.readMessage(com.grpc.proto.smartproto.PMHistoryEntry.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              ozoneHistory_ = new java.util.ArrayList<com.grpc.proto.smartproto.OzoneHistoryEntry>();
              mutable_bitField0_ |= 0x00000008;
            }
            ozoneHistory_.add(
                input.readMessage(com.grpc.proto.smartproto.OzoneHistoryEntry.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        pm25History_ = java.util.Collections.unmodifiableList(pm25History_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        pm10History_ = java.util.Collections.unmodifiableList(pm10History_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        ozoneHistory_ = java.util.Collections.unmodifiableList(ozoneHistory_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_AirQualitySummaryHistory_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_AirQualitySummaryHistory_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.proto.smartproto.AirQualitySummaryHistory.class, com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder.class);
  }

  private int bitField0_;
  public static final int AREA_FIELD_NUMBER = 1;
  private volatile java.lang.Object area_;
  /**
   * <code>string area = 1;</code>
   */
  public java.lang.String getArea() {
    java.lang.Object ref = area_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      area_ = s;
      return s;
    }
  }
  /**
   * <code>string area = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAreaBytes() {
    java.lang.Object ref = area_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      area_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PM25HISTORY_FIELD_NUMBER = 2;
  private java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> pm25History_;
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  public java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> getPm25HistoryList() {
    return pm25History_;
  }
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  public java.util.List<? extends com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
      getPm25HistoryOrBuilderList() {
    return pm25History_;
  }
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  public int getPm25HistoryCount() {
    return pm25History_.size();
  }
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  public com.grpc.proto.smartproto.PMHistoryEntry getPm25History(int index) {
    return pm25History_.get(index);
  }
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  public com.grpc.proto.smartproto.PMHistoryEntryOrBuilder getPm25HistoryOrBuilder(
      int index) {
    return pm25History_.get(index);
  }

  public static final int PM10HISTORY_FIELD_NUMBER = 3;
  private java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> pm10History_;
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  public java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> getPm10HistoryList() {
    return pm10History_;
  }
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  public java.util.List<? extends com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
      getPm10HistoryOrBuilderList() {
    return pm10History_;
  }
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  public int getPm10HistoryCount() {
    return pm10History_.size();
  }
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  public com.grpc.proto.smartproto.PMHistoryEntry getPm10History(int index) {
    return pm10History_.get(index);
  }
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  public com.grpc.proto.smartproto.PMHistoryEntryOrBuilder getPm10HistoryOrBuilder(
      int index) {
    return pm10History_.get(index);
  }

  public static final int OZONEHISTORY_FIELD_NUMBER = 4;
  private java.util.List<com.grpc.proto.smartproto.OzoneHistoryEntry> ozoneHistory_;
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  public java.util.List<com.grpc.proto.smartproto.OzoneHistoryEntry> getOzoneHistoryList() {
    return ozoneHistory_;
  }
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  public java.util.List<? extends com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder> 
      getOzoneHistoryOrBuilderList() {
    return ozoneHistory_;
  }
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  public int getOzoneHistoryCount() {
    return ozoneHistory_.size();
  }
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  public com.grpc.proto.smartproto.OzoneHistoryEntry getOzoneHistory(int index) {
    return ozoneHistory_.get(index);
  }
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  public com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder getOzoneHistoryOrBuilder(
      int index) {
    return ozoneHistory_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAreaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, area_);
    }
    for (int i = 0; i < pm25History_.size(); i++) {
      output.writeMessage(2, pm25History_.get(i));
    }
    for (int i = 0; i < pm10History_.size(); i++) {
      output.writeMessage(3, pm10History_.get(i));
    }
    for (int i = 0; i < ozoneHistory_.size(); i++) {
      output.writeMessage(4, ozoneHistory_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAreaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, area_);
    }
    for (int i = 0; i < pm25History_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, pm25History_.get(i));
    }
    for (int i = 0; i < pm10History_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, pm10History_.get(i));
    }
    for (int i = 0; i < ozoneHistory_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, ozoneHistory_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.proto.smartproto.AirQualitySummaryHistory)) {
      return super.equals(obj);
    }
    com.grpc.proto.smartproto.AirQualitySummaryHistory other = (com.grpc.proto.smartproto.AirQualitySummaryHistory) obj;

    boolean result = true;
    result = result && getArea()
        .equals(other.getArea());
    result = result && getPm25HistoryList()
        .equals(other.getPm25HistoryList());
    result = result && getPm10HistoryList()
        .equals(other.getPm10HistoryList());
    result = result && getOzoneHistoryList()
        .equals(other.getOzoneHistoryList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AREA_FIELD_NUMBER;
    hash = (53 * hash) + getArea().hashCode();
    if (getPm25HistoryCount() > 0) {
      hash = (37 * hash) + PM25HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getPm25HistoryList().hashCode();
    }
    if (getPm10HistoryCount() > 0) {
      hash = (37 * hash) + PM10HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getPm10HistoryList().hashCode();
    }
    if (getOzoneHistoryCount() > 0) {
      hash = (37 * hash) + OZONEHISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getOzoneHistoryList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.AirQualitySummaryHistory parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.proto.smartproto.AirQualitySummaryHistory prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartproto.AirQualitySummaryHistory}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartproto.AirQualitySummaryHistory)
      com.grpc.proto.smartproto.AirQualitySummaryHistoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_AirQualitySummaryHistory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_AirQualitySummaryHistory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.proto.smartproto.AirQualitySummaryHistory.class, com.grpc.proto.smartproto.AirQualitySummaryHistory.Builder.class);
    }

    // Construct using com.grpc.proto.smartproto.AirQualitySummaryHistory.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPm25HistoryFieldBuilder();
        getPm10HistoryFieldBuilder();
        getOzoneHistoryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      area_ = "";

      if (pm25HistoryBuilder_ == null) {
        pm25History_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        pm25HistoryBuilder_.clear();
      }
      if (pm10HistoryBuilder_ == null) {
        pm10History_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        pm10HistoryBuilder_.clear();
      }
      if (ozoneHistoryBuilder_ == null) {
        ozoneHistory_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        ozoneHistoryBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.proto.smartproto.HistoryDataProtoImpl.internal_static_smartproto_AirQualitySummaryHistory_descriptor;
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.AirQualitySummaryHistory getDefaultInstanceForType() {
      return com.grpc.proto.smartproto.AirQualitySummaryHistory.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.AirQualitySummaryHistory build() {
      com.grpc.proto.smartproto.AirQualitySummaryHistory result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.AirQualitySummaryHistory buildPartial() {
      com.grpc.proto.smartproto.AirQualitySummaryHistory result = new com.grpc.proto.smartproto.AirQualitySummaryHistory(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.area_ = area_;
      if (pm25HistoryBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          pm25History_ = java.util.Collections.unmodifiableList(pm25History_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.pm25History_ = pm25History_;
      } else {
        result.pm25History_ = pm25HistoryBuilder_.build();
      }
      if (pm10HistoryBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          pm10History_ = java.util.Collections.unmodifiableList(pm10History_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.pm10History_ = pm10History_;
      } else {
        result.pm10History_ = pm10HistoryBuilder_.build();
      }
      if (ozoneHistoryBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          ozoneHistory_ = java.util.Collections.unmodifiableList(ozoneHistory_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.ozoneHistory_ = ozoneHistory_;
      } else {
        result.ozoneHistory_ = ozoneHistoryBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.proto.smartproto.AirQualitySummaryHistory) {
        return mergeFrom((com.grpc.proto.smartproto.AirQualitySummaryHistory)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.proto.smartproto.AirQualitySummaryHistory other) {
      if (other == com.grpc.proto.smartproto.AirQualitySummaryHistory.getDefaultInstance()) return this;
      if (!other.getArea().isEmpty()) {
        area_ = other.area_;
        onChanged();
      }
      if (pm25HistoryBuilder_ == null) {
        if (!other.pm25History_.isEmpty()) {
          if (pm25History_.isEmpty()) {
            pm25History_ = other.pm25History_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePm25HistoryIsMutable();
            pm25History_.addAll(other.pm25History_);
          }
          onChanged();
        }
      } else {
        if (!other.pm25History_.isEmpty()) {
          if (pm25HistoryBuilder_.isEmpty()) {
            pm25HistoryBuilder_.dispose();
            pm25HistoryBuilder_ = null;
            pm25History_ = other.pm25History_;
            bitField0_ = (bitField0_ & ~0x00000002);
            pm25HistoryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPm25HistoryFieldBuilder() : null;
          } else {
            pm25HistoryBuilder_.addAllMessages(other.pm25History_);
          }
        }
      }
      if (pm10HistoryBuilder_ == null) {
        if (!other.pm10History_.isEmpty()) {
          if (pm10History_.isEmpty()) {
            pm10History_ = other.pm10History_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePm10HistoryIsMutable();
            pm10History_.addAll(other.pm10History_);
          }
          onChanged();
        }
      } else {
        if (!other.pm10History_.isEmpty()) {
          if (pm10HistoryBuilder_.isEmpty()) {
            pm10HistoryBuilder_.dispose();
            pm10HistoryBuilder_ = null;
            pm10History_ = other.pm10History_;
            bitField0_ = (bitField0_ & ~0x00000004);
            pm10HistoryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPm10HistoryFieldBuilder() : null;
          } else {
            pm10HistoryBuilder_.addAllMessages(other.pm10History_);
          }
        }
      }
      if (ozoneHistoryBuilder_ == null) {
        if (!other.ozoneHistory_.isEmpty()) {
          if (ozoneHistory_.isEmpty()) {
            ozoneHistory_ = other.ozoneHistory_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureOzoneHistoryIsMutable();
            ozoneHistory_.addAll(other.ozoneHistory_);
          }
          onChanged();
        }
      } else {
        if (!other.ozoneHistory_.isEmpty()) {
          if (ozoneHistoryBuilder_.isEmpty()) {
            ozoneHistoryBuilder_.dispose();
            ozoneHistoryBuilder_ = null;
            ozoneHistory_ = other.ozoneHistory_;
            bitField0_ = (bitField0_ & ~0x00000008);
            ozoneHistoryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOzoneHistoryFieldBuilder() : null;
          } else {
            ozoneHistoryBuilder_.addAllMessages(other.ozoneHistory_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.proto.smartproto.AirQualitySummaryHistory parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.proto.smartproto.AirQualitySummaryHistory) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object area_ = "";
    /**
     * <code>string area = 1;</code>
     */
    public java.lang.String getArea() {
      java.lang.Object ref = area_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        area_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string area = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAreaBytes() {
      java.lang.Object ref = area_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        area_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string area = 1;</code>
     */
    public Builder setArea(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      area_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string area = 1;</code>
     */
    public Builder clearArea() {
      
      area_ = getDefaultInstance().getArea();
      onChanged();
      return this;
    }
    /**
     * <code>string area = 1;</code>
     */
    public Builder setAreaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      area_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> pm25History_ =
      java.util.Collections.emptyList();
    private void ensurePm25HistoryIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        pm25History_ = new java.util.ArrayList<com.grpc.proto.smartproto.PMHistoryEntry>(pm25History_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.PMHistoryEntry, com.grpc.proto.smartproto.PMHistoryEntry.Builder, com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> pm25HistoryBuilder_;

    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> getPm25HistoryList() {
      if (pm25HistoryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pm25History_);
      } else {
        return pm25HistoryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public int getPm25HistoryCount() {
      if (pm25HistoryBuilder_ == null) {
        return pm25History_.size();
      } else {
        return pm25HistoryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntry getPm25History(int index) {
      if (pm25HistoryBuilder_ == null) {
        return pm25History_.get(index);
      } else {
        return pm25HistoryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder setPm25History(
        int index, com.grpc.proto.smartproto.PMHistoryEntry value) {
      if (pm25HistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePm25HistoryIsMutable();
        pm25History_.set(index, value);
        onChanged();
      } else {
        pm25HistoryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder setPm25History(
        int index, com.grpc.proto.smartproto.PMHistoryEntry.Builder builderForValue) {
      if (pm25HistoryBuilder_ == null) {
        ensurePm25HistoryIsMutable();
        pm25History_.set(index, builderForValue.build());
        onChanged();
      } else {
        pm25HistoryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder addPm25History(com.grpc.proto.smartproto.PMHistoryEntry value) {
      if (pm25HistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePm25HistoryIsMutable();
        pm25History_.add(value);
        onChanged();
      } else {
        pm25HistoryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder addPm25History(
        int index, com.grpc.proto.smartproto.PMHistoryEntry value) {
      if (pm25HistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePm25HistoryIsMutable();
        pm25History_.add(index, value);
        onChanged();
      } else {
        pm25HistoryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder addPm25History(
        com.grpc.proto.smartproto.PMHistoryEntry.Builder builderForValue) {
      if (pm25HistoryBuilder_ == null) {
        ensurePm25HistoryIsMutable();
        pm25History_.add(builderForValue.build());
        onChanged();
      } else {
        pm25HistoryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder addPm25History(
        int index, com.grpc.proto.smartproto.PMHistoryEntry.Builder builderForValue) {
      if (pm25HistoryBuilder_ == null) {
        ensurePm25HistoryIsMutable();
        pm25History_.add(index, builderForValue.build());
        onChanged();
      } else {
        pm25HistoryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder addAllPm25History(
        java.lang.Iterable<? extends com.grpc.proto.smartproto.PMHistoryEntry> values) {
      if (pm25HistoryBuilder_ == null) {
        ensurePm25HistoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pm25History_);
        onChanged();
      } else {
        pm25HistoryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder clearPm25History() {
      if (pm25HistoryBuilder_ == null) {
        pm25History_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        pm25HistoryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public Builder removePm25History(int index) {
      if (pm25HistoryBuilder_ == null) {
        ensurePm25HistoryIsMutable();
        pm25History_.remove(index);
        onChanged();
      } else {
        pm25HistoryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntry.Builder getPm25HistoryBuilder(
        int index) {
      return getPm25HistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntryOrBuilder getPm25HistoryOrBuilder(
        int index) {
      if (pm25HistoryBuilder_ == null) {
        return pm25History_.get(index);  } else {
        return pm25HistoryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public java.util.List<? extends com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
         getPm25HistoryOrBuilderList() {
      if (pm25HistoryBuilder_ != null) {
        return pm25HistoryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pm25History_);
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntry.Builder addPm25HistoryBuilder() {
      return getPm25HistoryFieldBuilder().addBuilder(
          com.grpc.proto.smartproto.PMHistoryEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntry.Builder addPm25HistoryBuilder(
        int index) {
      return getPm25HistoryFieldBuilder().addBuilder(
          index, com.grpc.proto.smartproto.PMHistoryEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.PMHistoryEntry.Builder> 
         getPm25HistoryBuilderList() {
      return getPm25HistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.PMHistoryEntry, com.grpc.proto.smartproto.PMHistoryEntry.Builder, com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
        getPm25HistoryFieldBuilder() {
      if (pm25HistoryBuilder_ == null) {
        pm25HistoryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.proto.smartproto.PMHistoryEntry, com.grpc.proto.smartproto.PMHistoryEntry.Builder, com.grpc.proto.smartproto.PMHistoryEntryOrBuilder>(
                pm25History_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        pm25History_ = null;
      }
      return pm25HistoryBuilder_;
    }

    private java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> pm10History_ =
      java.util.Collections.emptyList();
    private void ensurePm10HistoryIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        pm10History_ = new java.util.ArrayList<com.grpc.proto.smartproto.PMHistoryEntry>(pm10History_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.PMHistoryEntry, com.grpc.proto.smartproto.PMHistoryEntry.Builder, com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> pm10HistoryBuilder_;

    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> getPm10HistoryList() {
      if (pm10HistoryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pm10History_);
      } else {
        return pm10HistoryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public int getPm10HistoryCount() {
      if (pm10HistoryBuilder_ == null) {
        return pm10History_.size();
      } else {
        return pm10HistoryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntry getPm10History(int index) {
      if (pm10HistoryBuilder_ == null) {
        return pm10History_.get(index);
      } else {
        return pm10HistoryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder setPm10History(
        int index, com.grpc.proto.smartproto.PMHistoryEntry value) {
      if (pm10HistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePm10HistoryIsMutable();
        pm10History_.set(index, value);
        onChanged();
      } else {
        pm10HistoryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder setPm10History(
        int index, com.grpc.proto.smartproto.PMHistoryEntry.Builder builderForValue) {
      if (pm10HistoryBuilder_ == null) {
        ensurePm10HistoryIsMutable();
        pm10History_.set(index, builderForValue.build());
        onChanged();
      } else {
        pm10HistoryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder addPm10History(com.grpc.proto.smartproto.PMHistoryEntry value) {
      if (pm10HistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePm10HistoryIsMutable();
        pm10History_.add(value);
        onChanged();
      } else {
        pm10HistoryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder addPm10History(
        int index, com.grpc.proto.smartproto.PMHistoryEntry value) {
      if (pm10HistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePm10HistoryIsMutable();
        pm10History_.add(index, value);
        onChanged();
      } else {
        pm10HistoryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder addPm10History(
        com.grpc.proto.smartproto.PMHistoryEntry.Builder builderForValue) {
      if (pm10HistoryBuilder_ == null) {
        ensurePm10HistoryIsMutable();
        pm10History_.add(builderForValue.build());
        onChanged();
      } else {
        pm10HistoryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder addPm10History(
        int index, com.grpc.proto.smartproto.PMHistoryEntry.Builder builderForValue) {
      if (pm10HistoryBuilder_ == null) {
        ensurePm10HistoryIsMutable();
        pm10History_.add(index, builderForValue.build());
        onChanged();
      } else {
        pm10HistoryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder addAllPm10History(
        java.lang.Iterable<? extends com.grpc.proto.smartproto.PMHistoryEntry> values) {
      if (pm10HistoryBuilder_ == null) {
        ensurePm10HistoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pm10History_);
        onChanged();
      } else {
        pm10HistoryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder clearPm10History() {
      if (pm10HistoryBuilder_ == null) {
        pm10History_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        pm10HistoryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public Builder removePm10History(int index) {
      if (pm10HistoryBuilder_ == null) {
        ensurePm10HistoryIsMutable();
        pm10History_.remove(index);
        onChanged();
      } else {
        pm10HistoryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntry.Builder getPm10HistoryBuilder(
        int index) {
      return getPm10HistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntryOrBuilder getPm10HistoryOrBuilder(
        int index) {
      if (pm10HistoryBuilder_ == null) {
        return pm10History_.get(index);  } else {
        return pm10HistoryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public java.util.List<? extends com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
         getPm10HistoryOrBuilderList() {
      if (pm10HistoryBuilder_ != null) {
        return pm10HistoryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pm10History_);
      }
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntry.Builder addPm10HistoryBuilder() {
      return getPm10HistoryFieldBuilder().addBuilder(
          com.grpc.proto.smartproto.PMHistoryEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public com.grpc.proto.smartproto.PMHistoryEntry.Builder addPm10HistoryBuilder(
        int index) {
      return getPm10HistoryFieldBuilder().addBuilder(
          index, com.grpc.proto.smartproto.PMHistoryEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.PMHistoryEntry.Builder> 
         getPm10HistoryBuilderList() {
      return getPm10HistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.PMHistoryEntry, com.grpc.proto.smartproto.PMHistoryEntry.Builder, com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
        getPm10HistoryFieldBuilder() {
      if (pm10HistoryBuilder_ == null) {
        pm10HistoryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.proto.smartproto.PMHistoryEntry, com.grpc.proto.smartproto.PMHistoryEntry.Builder, com.grpc.proto.smartproto.PMHistoryEntryOrBuilder>(
                pm10History_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        pm10History_ = null;
      }
      return pm10HistoryBuilder_;
    }

    private java.util.List<com.grpc.proto.smartproto.OzoneHistoryEntry> ozoneHistory_ =
      java.util.Collections.emptyList();
    private void ensureOzoneHistoryIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        ozoneHistory_ = new java.util.ArrayList<com.grpc.proto.smartproto.OzoneHistoryEntry>(ozoneHistory_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.OzoneHistoryEntry, com.grpc.proto.smartproto.OzoneHistoryEntry.Builder, com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder> ozoneHistoryBuilder_;

    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.OzoneHistoryEntry> getOzoneHistoryList() {
      if (ozoneHistoryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ozoneHistory_);
      } else {
        return ozoneHistoryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public int getOzoneHistoryCount() {
      if (ozoneHistoryBuilder_ == null) {
        return ozoneHistory_.size();
      } else {
        return ozoneHistoryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public com.grpc.proto.smartproto.OzoneHistoryEntry getOzoneHistory(int index) {
      if (ozoneHistoryBuilder_ == null) {
        return ozoneHistory_.get(index);
      } else {
        return ozoneHistoryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder setOzoneHistory(
        int index, com.grpc.proto.smartproto.OzoneHistoryEntry value) {
      if (ozoneHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOzoneHistoryIsMutable();
        ozoneHistory_.set(index, value);
        onChanged();
      } else {
        ozoneHistoryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder setOzoneHistory(
        int index, com.grpc.proto.smartproto.OzoneHistoryEntry.Builder builderForValue) {
      if (ozoneHistoryBuilder_ == null) {
        ensureOzoneHistoryIsMutable();
        ozoneHistory_.set(index, builderForValue.build());
        onChanged();
      } else {
        ozoneHistoryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder addOzoneHistory(com.grpc.proto.smartproto.OzoneHistoryEntry value) {
      if (ozoneHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOzoneHistoryIsMutable();
        ozoneHistory_.add(value);
        onChanged();
      } else {
        ozoneHistoryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder addOzoneHistory(
        int index, com.grpc.proto.smartproto.OzoneHistoryEntry value) {
      if (ozoneHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOzoneHistoryIsMutable();
        ozoneHistory_.add(index, value);
        onChanged();
      } else {
        ozoneHistoryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder addOzoneHistory(
        com.grpc.proto.smartproto.OzoneHistoryEntry.Builder builderForValue) {
      if (ozoneHistoryBuilder_ == null) {
        ensureOzoneHistoryIsMutable();
        ozoneHistory_.add(builderForValue.build());
        onChanged();
      } else {
        ozoneHistoryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder addOzoneHistory(
        int index, com.grpc.proto.smartproto.OzoneHistoryEntry.Builder builderForValue) {
      if (ozoneHistoryBuilder_ == null) {
        ensureOzoneHistoryIsMutable();
        ozoneHistory_.add(index, builderForValue.build());
        onChanged();
      } else {
        ozoneHistoryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder addAllOzoneHistory(
        java.lang.Iterable<? extends com.grpc.proto.smartproto.OzoneHistoryEntry> values) {
      if (ozoneHistoryBuilder_ == null) {
        ensureOzoneHistoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ozoneHistory_);
        onChanged();
      } else {
        ozoneHistoryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder clearOzoneHistory() {
      if (ozoneHistoryBuilder_ == null) {
        ozoneHistory_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        ozoneHistoryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public Builder removeOzoneHistory(int index) {
      if (ozoneHistoryBuilder_ == null) {
        ensureOzoneHistoryIsMutable();
        ozoneHistory_.remove(index);
        onChanged();
      } else {
        ozoneHistoryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public com.grpc.proto.smartproto.OzoneHistoryEntry.Builder getOzoneHistoryBuilder(
        int index) {
      return getOzoneHistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder getOzoneHistoryOrBuilder(
        int index) {
      if (ozoneHistoryBuilder_ == null) {
        return ozoneHistory_.get(index);  } else {
        return ozoneHistoryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public java.util.List<? extends com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder> 
         getOzoneHistoryOrBuilderList() {
      if (ozoneHistoryBuilder_ != null) {
        return ozoneHistoryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ozoneHistory_);
      }
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public com.grpc.proto.smartproto.OzoneHistoryEntry.Builder addOzoneHistoryBuilder() {
      return getOzoneHistoryFieldBuilder().addBuilder(
          com.grpc.proto.smartproto.OzoneHistoryEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public com.grpc.proto.smartproto.OzoneHistoryEntry.Builder addOzoneHistoryBuilder(
        int index) {
      return getOzoneHistoryFieldBuilder().addBuilder(
          index, com.grpc.proto.smartproto.OzoneHistoryEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.OzoneHistoryEntry.Builder> 
         getOzoneHistoryBuilderList() {
      return getOzoneHistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.OzoneHistoryEntry, com.grpc.proto.smartproto.OzoneHistoryEntry.Builder, com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder> 
        getOzoneHistoryFieldBuilder() {
      if (ozoneHistoryBuilder_ == null) {
        ozoneHistoryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.proto.smartproto.OzoneHistoryEntry, com.grpc.proto.smartproto.OzoneHistoryEntry.Builder, com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder>(
                ozoneHistory_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        ozoneHistory_ = null;
      }
      return ozoneHistoryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartproto.AirQualitySummaryHistory)
  }

  // @@protoc_insertion_point(class_scope:smartproto.AirQualitySummaryHistory)
  private static final com.grpc.proto.smartproto.AirQualitySummaryHistory DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.proto.smartproto.AirQualitySummaryHistory();
  }

  public static com.grpc.proto.smartproto.AirQualitySummaryHistory getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AirQualitySummaryHistory>
      PARSER = new com.google.protobuf.AbstractParser<AirQualitySummaryHistory>() {
    @java.lang.Override
    public AirQualitySummaryHistory parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AirQualitySummaryHistory(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AirQualitySummaryHistory> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AirQualitySummaryHistory> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.proto.smartproto.AirQualitySummaryHistory getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

