// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public interface AirQualityByLocationHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.AirQualityByLocationHistory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> 
      getPm25HistoryList();
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  com.grpc.proto.smartproto.PMHistoryEntry getPm25History(int index);
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  int getPm25HistoryCount();
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
      getPm25HistoryOrBuilderList();
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm25History = 2;</code>
   */
  com.grpc.proto.smartproto.PMHistoryEntryOrBuilder getPm25HistoryOrBuilder(
      int index);

  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> 
      getPm10HistoryList();
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  com.grpc.proto.smartproto.PMHistoryEntry getPm10History(int index);
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  int getPm10HistoryCount();
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
      getPm10HistoryOrBuilderList();
  /**
   * <code>repeated .smartproto.PMHistoryEntry pm10History = 3;</code>
   */
  com.grpc.proto.smartproto.PMHistoryEntryOrBuilder getPm10HistoryOrBuilder(
      int index);

  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  java.util.List<com.grpc.proto.smartproto.OzoneHistoryEntry> 
      getOzoneHistoryList();
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  com.grpc.proto.smartproto.OzoneHistoryEntry getOzoneHistory(int index);
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  int getOzoneHistoryCount();
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder> 
      getOzoneHistoryOrBuilderList();
  /**
   * <code>repeated .smartproto.OzoneHistoryEntry ozoneHistory = 4;</code>
   */
  com.grpc.proto.smartproto.OzoneHistoryEntryOrBuilder getOzoneHistoryOrBuilder(
      int index);
}
