// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allerts.proto

package com.grpc.proto.smartproto;

public interface AlertCreationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.AlertCreationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alert_id = 1;</code>
   */
  java.lang.String getAlertId();
  /**
   * <code>string alert_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertIdBytes();
}
