// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allerts.proto

package com.grpc.proto.smartproto;

public interface AlertDeletionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.AlertDeletionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string alert_id = 2;</code>
   */
  java.lang.String getAlertId();
  /**
   * <code>string alert_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getAlertIdBytes();
}
