// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public interface HistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.HistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string area = 2;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 2;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <pre>
   * Number of days to retrieve historical data for
   * </pre>
   *
   * <code>int32 days = 3;</code>
   */
  int getDays();
}
