// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allerts.proto

package com.grpc.proto.smartproto;

public interface ListAlertsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.ListAlertsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .smartproto.UserAlert alerts = 1;</code>
   */
  java.util.List<com.grpc.proto.smartproto.UserAlert> 
      getAlertsList();
  /**
   * <code>repeated .smartproto.UserAlert alerts = 1;</code>
   */
  com.grpc.proto.smartproto.UserAlert getAlerts(int index);
  /**
   * <code>repeated .smartproto.UserAlert alerts = 1;</code>
   */
  int getAlertsCount();
  /**
   * <code>repeated .smartproto.UserAlert alerts = 1;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.UserAlertOrBuilder> 
      getAlertsOrBuilderList();
  /**
   * <code>repeated .smartproto.UserAlert alerts = 1;</code>
   */
  com.grpc.proto.smartproto.UserAlertOrBuilder getAlertsOrBuilder(
      int index);
}
