// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimedata.proto

package com.grpc.proto.smartproto;

/**
 * Protobuf type {@code smartproto.LocationResponse}
 */
public  final class LocationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartproto.LocationResponse)
    LocationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocationResponse.newBuilder() to construct.
  private LocationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocationResponse() {
    airQualityList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              airQualityList_ = new java.util.ArrayList<com.grpc.proto.smartproto.AirQualityByLocation>();
              mutable_bitField0_ |= 0x00000001;
            }
            airQualityList_.add(
                input.readMessage(com.grpc.proto.smartproto.AirQualityByLocation.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        airQualityList_ = java.util.Collections.unmodifiableList(airQualityList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_LocationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_LocationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.proto.smartproto.LocationResponse.class, com.grpc.proto.smartproto.LocationResponse.Builder.class);
  }

  public static final int AIRQUALITYLIST_FIELD_NUMBER = 1;
  private java.util.List<com.grpc.proto.smartproto.AirQualityByLocation> airQualityList_;
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  public java.util.List<com.grpc.proto.smartproto.AirQualityByLocation> getAirQualityListList() {
    return airQualityList_;
  }
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  public java.util.List<? extends com.grpc.proto.smartproto.AirQualityByLocationOrBuilder> 
      getAirQualityListOrBuilderList() {
    return airQualityList_;
  }
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  public int getAirQualityListCount() {
    return airQualityList_.size();
  }
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  public com.grpc.proto.smartproto.AirQualityByLocation getAirQualityList(int index) {
    return airQualityList_.get(index);
  }
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  public com.grpc.proto.smartproto.AirQualityByLocationOrBuilder getAirQualityListOrBuilder(
      int index) {
    return airQualityList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < airQualityList_.size(); i++) {
      output.writeMessage(1, airQualityList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < airQualityList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, airQualityList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.proto.smartproto.LocationResponse)) {
      return super.equals(obj);
    }
    com.grpc.proto.smartproto.LocationResponse other = (com.grpc.proto.smartproto.LocationResponse) obj;

    boolean result = true;
    result = result && getAirQualityListList()
        .equals(other.getAirQualityListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAirQualityListCount() > 0) {
      hash = (37 * hash) + AIRQUALITYLIST_FIELD_NUMBER;
      hash = (53 * hash) + getAirQualityListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.proto.smartproto.LocationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.proto.smartproto.LocationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.proto.smartproto.LocationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartproto.LocationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartproto.LocationResponse)
      com.grpc.proto.smartproto.LocationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_LocationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_LocationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.proto.smartproto.LocationResponse.class, com.grpc.proto.smartproto.LocationResponse.Builder.class);
    }

    // Construct using com.grpc.proto.smartproto.LocationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAirQualityListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (airQualityListBuilder_ == null) {
        airQualityList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        airQualityListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.proto.smartproto.SmartProtoImpl.internal_static_smartproto_LocationResponse_descriptor;
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.LocationResponse getDefaultInstanceForType() {
      return com.grpc.proto.smartproto.LocationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.LocationResponse build() {
      com.grpc.proto.smartproto.LocationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.proto.smartproto.LocationResponse buildPartial() {
      com.grpc.proto.smartproto.LocationResponse result = new com.grpc.proto.smartproto.LocationResponse(this);
      int from_bitField0_ = bitField0_;
      if (airQualityListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          airQualityList_ = java.util.Collections.unmodifiableList(airQualityList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.airQualityList_ = airQualityList_;
      } else {
        result.airQualityList_ = airQualityListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.proto.smartproto.LocationResponse) {
        return mergeFrom((com.grpc.proto.smartproto.LocationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.proto.smartproto.LocationResponse other) {
      if (other == com.grpc.proto.smartproto.LocationResponse.getDefaultInstance()) return this;
      if (airQualityListBuilder_ == null) {
        if (!other.airQualityList_.isEmpty()) {
          if (airQualityList_.isEmpty()) {
            airQualityList_ = other.airQualityList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAirQualityListIsMutable();
            airQualityList_.addAll(other.airQualityList_);
          }
          onChanged();
        }
      } else {
        if (!other.airQualityList_.isEmpty()) {
          if (airQualityListBuilder_.isEmpty()) {
            airQualityListBuilder_.dispose();
            airQualityListBuilder_ = null;
            airQualityList_ = other.airQualityList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            airQualityListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAirQualityListFieldBuilder() : null;
          } else {
            airQualityListBuilder_.addAllMessages(other.airQualityList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.proto.smartproto.LocationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.proto.smartproto.LocationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.grpc.proto.smartproto.AirQualityByLocation> airQualityList_ =
      java.util.Collections.emptyList();
    private void ensureAirQualityListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        airQualityList_ = new java.util.ArrayList<com.grpc.proto.smartproto.AirQualityByLocation>(airQualityList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.AirQualityByLocation, com.grpc.proto.smartproto.AirQualityByLocation.Builder, com.grpc.proto.smartproto.AirQualityByLocationOrBuilder> airQualityListBuilder_;

    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.AirQualityByLocation> getAirQualityListList() {
      if (airQualityListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(airQualityList_);
      } else {
        return airQualityListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public int getAirQualityListCount() {
      if (airQualityListBuilder_ == null) {
        return airQualityList_.size();
      } else {
        return airQualityListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualityByLocation getAirQualityList(int index) {
      if (airQualityListBuilder_ == null) {
        return airQualityList_.get(index);
      } else {
        return airQualityListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder setAirQualityList(
        int index, com.grpc.proto.smartproto.AirQualityByLocation value) {
      if (airQualityListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAirQualityListIsMutable();
        airQualityList_.set(index, value);
        onChanged();
      } else {
        airQualityListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder setAirQualityList(
        int index, com.grpc.proto.smartproto.AirQualityByLocation.Builder builderForValue) {
      if (airQualityListBuilder_ == null) {
        ensureAirQualityListIsMutable();
        airQualityList_.set(index, builderForValue.build());
        onChanged();
      } else {
        airQualityListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder addAirQualityList(com.grpc.proto.smartproto.AirQualityByLocation value) {
      if (airQualityListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAirQualityListIsMutable();
        airQualityList_.add(value);
        onChanged();
      } else {
        airQualityListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder addAirQualityList(
        int index, com.grpc.proto.smartproto.AirQualityByLocation value) {
      if (airQualityListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAirQualityListIsMutable();
        airQualityList_.add(index, value);
        onChanged();
      } else {
        airQualityListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder addAirQualityList(
        com.grpc.proto.smartproto.AirQualityByLocation.Builder builderForValue) {
      if (airQualityListBuilder_ == null) {
        ensureAirQualityListIsMutable();
        airQualityList_.add(builderForValue.build());
        onChanged();
      } else {
        airQualityListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder addAirQualityList(
        int index, com.grpc.proto.smartproto.AirQualityByLocation.Builder builderForValue) {
      if (airQualityListBuilder_ == null) {
        ensureAirQualityListIsMutable();
        airQualityList_.add(index, builderForValue.build());
        onChanged();
      } else {
        airQualityListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder addAllAirQualityList(
        java.lang.Iterable<? extends com.grpc.proto.smartproto.AirQualityByLocation> values) {
      if (airQualityListBuilder_ == null) {
        ensureAirQualityListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, airQualityList_);
        onChanged();
      } else {
        airQualityListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder clearAirQualityList() {
      if (airQualityListBuilder_ == null) {
        airQualityList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        airQualityListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public Builder removeAirQualityList(int index) {
      if (airQualityListBuilder_ == null) {
        ensureAirQualityListIsMutable();
        airQualityList_.remove(index);
        onChanged();
      } else {
        airQualityListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualityByLocation.Builder getAirQualityListBuilder(
        int index) {
      return getAirQualityListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualityByLocationOrBuilder getAirQualityListOrBuilder(
        int index) {
      if (airQualityListBuilder_ == null) {
        return airQualityList_.get(index);  } else {
        return airQualityListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public java.util.List<? extends com.grpc.proto.smartproto.AirQualityByLocationOrBuilder> 
         getAirQualityListOrBuilderList() {
      if (airQualityListBuilder_ != null) {
        return airQualityListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(airQualityList_);
      }
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualityByLocation.Builder addAirQualityListBuilder() {
      return getAirQualityListFieldBuilder().addBuilder(
          com.grpc.proto.smartproto.AirQualityByLocation.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public com.grpc.proto.smartproto.AirQualityByLocation.Builder addAirQualityListBuilder(
        int index) {
      return getAirQualityListFieldBuilder().addBuilder(
          index, com.grpc.proto.smartproto.AirQualityByLocation.getDefaultInstance());
    }
    /**
     * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
     */
    public java.util.List<com.grpc.proto.smartproto.AirQualityByLocation.Builder> 
         getAirQualityListBuilderList() {
      return getAirQualityListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.proto.smartproto.AirQualityByLocation, com.grpc.proto.smartproto.AirQualityByLocation.Builder, com.grpc.proto.smartproto.AirQualityByLocationOrBuilder> 
        getAirQualityListFieldBuilder() {
      if (airQualityListBuilder_ == null) {
        airQualityListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.proto.smartproto.AirQualityByLocation, com.grpc.proto.smartproto.AirQualityByLocation.Builder, com.grpc.proto.smartproto.AirQualityByLocationOrBuilder>(
                airQualityList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        airQualityList_ = null;
      }
      return airQualityListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartproto.LocationResponse)
  }

  // @@protoc_insertion_point(class_scope:smartproto.LocationResponse)
  private static final com.grpc.proto.smartproto.LocationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.proto.smartproto.LocationResponse();
  }

  public static com.grpc.proto.smartproto.LocationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocationResponse>
      PARSER = new com.google.protobuf.AbstractParser<LocationResponse>() {
    @java.lang.Override
    public LocationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.proto.smartproto.LocationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

