// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public interface LocationHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.LocationHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .smartproto.AirQualityByLocationHistory airQualityList = 1;</code>
   */
  java.util.List<com.grpc.proto.smartproto.AirQualityByLocationHistory> 
      getAirQualityListList();
  /**
   * <code>repeated .smartproto.AirQualityByLocationHistory airQualityList = 1;</code>
   */
  com.grpc.proto.smartproto.AirQualityByLocationHistory getAirQualityList(int index);
  /**
   * <code>repeated .smartproto.AirQualityByLocationHistory airQualityList = 1;</code>
   */
  int getAirQualityListCount();
  /**
   * <code>repeated .smartproto.AirQualityByLocationHistory airQualityList = 1;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.AirQualityByLocationHistoryOrBuilder> 
      getAirQualityListOrBuilderList();
  /**
   * <code>repeated .smartproto.AirQualityByLocationHistory airQualityList = 1;</code>
   */
  com.grpc.proto.smartproto.AirQualityByLocationHistoryOrBuilder getAirQualityListOrBuilder(
      int index);
}
