// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimedata.proto

package com.grpc.proto.smartproto;

public interface LocationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.LocationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  java.util.List<com.grpc.proto.smartproto.AirQualityByLocation> 
      getAirQualityListList();
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  com.grpc.proto.smartproto.AirQualityByLocation getAirQualityList(int index);
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  int getAirQualityListCount();
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.AirQualityByLocationOrBuilder> 
      getAirQualityListOrBuilderList();
  /**
   * <code>repeated .smartproto.AirQualityByLocation airQualityList = 1;</code>
   */
  com.grpc.proto.smartproto.AirQualityByLocationOrBuilder getAirQualityListOrBuilder(
      int index);
}
