// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.grpc.proto.smartproto;

public interface PMHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.PMHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .smartproto.PMHistoryEntry entries = 1;</code>
   */
  java.util.List<com.grpc.proto.smartproto.PMHistoryEntry> 
      getEntriesList();
  /**
   * <code>repeated .smartproto.PMHistoryEntry entries = 1;</code>
   */
  com.grpc.proto.smartproto.PMHistoryEntry getEntries(int index);
  /**
   * <code>repeated .smartproto.PMHistoryEntry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .smartproto.PMHistoryEntry entries = 1;</code>
   */
  java.util.List<? extends com.grpc.proto.smartproto.PMHistoryEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .smartproto.PMHistoryEntry entries = 1;</code>
   */
  com.grpc.proto.smartproto.PMHistoryEntryOrBuilder getEntriesOrBuilder(
      int index);
}
