// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimedata.proto

package com.grpc.proto.smartproto;

public interface PMResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.PMResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float value = 1;</code>
   */
  float getValue();
}
