// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allerts.proto

package com.grpc.proto.smartproto;

public final class SmartAlertsProtoImpl {
  private SmartAlertsProtoImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_AlertCreationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_AlertCreationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_AlertCreationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_AlertCreationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_ListAlertsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_ListAlertsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_ListAlertsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_ListAlertsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_AlertDeletionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_AlertDeletionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_AlertDeletionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_AlertDeletionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartproto_UserAlert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartproto_UserAlert_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rallerts.proto\022\nsmartproto\"\215\001\n\024AlertCre" +
      "ationRequest\022\017\n\007user_id\030\001 \001(\t\022)\n\nalert_t" +
      "ype\030\002 \001(\0162\025.smartproto.AlertType\022&\n\010loca" +
      "tion\030\003 \001(\0132\024.smartproto.Location\022\021\n\tthre" +
      "shold\030\004 \001(\002\")\n\025AlertCreationResponse\022\020\n\010" +
      "alert_id\030\001 \001(\t\"$\n\021ListAlertsRequest\022\017\n\007u" +
      "ser_id\030\001 \001(\t\";\n\022ListAlertsResponse\022%\n\006al" +
      "erts\030\001 \003(\0132\025.smartproto.UserAlert\"9\n\024Ale" +
      "rtDeletionRequest\022\017\n\007user_id\030\001 \001(\t\022\020\n\010al" +
      "ert_id\030\002 \001(\t\"(\n\025AlertDeletionResponse\022\017\n" +
      "\007success\030\001 \001(\010\"/\n\010Location\022\020\n\010latitude\030\001" +
      " \001(\002\022\021\n\tlongitude\030\002 \001(\002\"\224\001\n\tUserAlert\022\020\n" +
      "\010alert_id\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\t\022)\n\naler" +
      "t_type\030\003 \001(\0162\025.smartproto.AlertType\022&\n\010l" +
      "ocation\030\004 \001(\0132\024.smartproto.Location\022\021\n\tt" +
      "hreshold\030\005 \001(\002**\n\tAlertType\022\010\n\004PM25\020\000\022\010\n" +
      "\004PM10\020\001\022\t\n\005OZONE\020\0022\226\002\n\031PersonalizedAlert" +
      "sService\022T\n\013CreateAlert\022 .smartproto.Ale" +
      "rtCreationRequest\032!.smartproto.AlertCrea" +
      "tionResponse\"\000\022M\n\nListAlerts\022\035.smartprot" +
      "o.ListAlertsRequest\032\036.smartproto.ListAle" +
      "rtsResponse\"\000\022T\n\013DeleteAlert\022 .smartprot" +
      "o.AlertDeletionRequest\032!.smartproto.Aler" +
      "tDeletionResponse\"\000B3\n\031com.grpc.proto.sm" +
      "artprotoB\024SmartAlertsProtoImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartproto_AlertCreationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartproto_AlertCreationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_AlertCreationRequest_descriptor,
        new java.lang.String[] { "UserId", "AlertType", "Location", "Threshold", });
    internal_static_smartproto_AlertCreationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartproto_AlertCreationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_AlertCreationResponse_descriptor,
        new java.lang.String[] { "AlertId", });
    internal_static_smartproto_ListAlertsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartproto_ListAlertsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_ListAlertsRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_smartproto_ListAlertsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartproto_ListAlertsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_ListAlertsResponse_descriptor,
        new java.lang.String[] { "Alerts", });
    internal_static_smartproto_AlertDeletionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smartproto_AlertDeletionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_AlertDeletionRequest_descriptor,
        new java.lang.String[] { "UserId", "AlertId", });
    internal_static_smartproto_AlertDeletionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_smartproto_AlertDeletionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_AlertDeletionResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_smartproto_Location_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_smartproto_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_Location_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_smartproto_UserAlert_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_smartproto_UserAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartproto_UserAlert_descriptor,
        new java.lang.String[] { "AlertId", "UserId", "AlertType", "Location", "Threshold", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
