// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allerts.proto

package com.grpc.proto.smartproto;

public interface UserAlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartproto.UserAlert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alert_id = 1;</code>
   */
  java.lang.String getAlertId();
  /**
   * <code>string alert_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertIdBytes();

  /**
   * <code>string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.smartproto.AlertType alert_type = 3;</code>
   */
  int getAlertTypeValue();
  /**
   * <code>.smartproto.AlertType alert_type = 3;</code>
   */
  com.grpc.proto.smartproto.AlertType getAlertType();

  /**
   * <code>.smartproto.Location location = 4;</code>
   */
  boolean hasLocation();
  /**
   * <code>.smartproto.Location location = 4;</code>
   */
  com.grpc.proto.smartproto.Location getLocation();
  /**
   * <code>.smartproto.Location location = 4;</code>
   */
  com.grpc.proto.smartproto.LocationOrBuilder getLocationOrBuilder();

  /**
   * <code>float threshold = 5;</code>
   */
  float getThreshold();
}
